# Generated by Django 5.2.2 on 2025-06-09 09:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=1000)),
                ('store_name', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(default='unknown', max_length=255)),
                ('receipt_type', models.CharField(default='unknown', max_length=255)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('all_items_price_with_tax', models.BooleanField(default=False)),
                ('payment_method', models.CharField(default='unknown', max_length=255)),
                ('rounding', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxes_not_included_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tips', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('measurement_unit', models.CharField(default='ks', max_length=50)),
                ('total_price_without_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price_with_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(default='Other', max_length=255)),
                ('item_price_with_tax', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scan.receiptimage')),
            ],
        ),
        migrations.CreateModel(
            name='TaxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_from_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_included', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_items', to='scan.receiptimage')),
            ],
        ),
    ]
