# Generated by Django 5.2.2 on 2025-08-13 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
        ('splits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='split',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splits', to='scan.receiptimage'),
        ),
        migrations.AddField(
            model_name='split',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
