# Generated by Django 5.2.2 on 2025-08-13 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
        ('splits', '0003_splitparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='assigned_items', to='splits.splitparticipant')),
                ('receipt_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scan.receiptitem')),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='splits.split')),
            ],
            options={
                'unique_together': {('split', 'receipt_item')},
            },
        ),
    ]
