# Generated by Django 5.2.2 on 2025-08-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splits', '0004_itemassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='finalization_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
